### ISSUE TITLE
smart-contracts: stay nft image is not showing anywhere (Mobile Metamask, Blockscout, etc.)

### ISSUE THREAD

**Issue by kvakes** [windingtree/videre-contracts#12]
NFT image should be shown here (but instead a default image of game controller is displayed): https://blockscout.com/xdai/mainnet/tokens/0xecff1da7acd4025c532c04db3b57b454bab95b4e/instance/1/token-transfers

Example of another token: https://blockscout.com/xdai/mainnet/tokens/0x22c1f6050e56d2876009903609a2cc3fef83b415/instance/4021638/token-transfers

![Screenshot from 2022-04-13 11-33-06](https://user-images.githubusercontent.com/377005/163146606-1104ec09-ba4f-492f-8385-badaa8ae7b95.png)
![Screenshot from 2022-04-13 11-32-15](https://user-images.githubusercontent.com/377005/163146615-54b347af-64b1-48b7-9828-dd7a54ef5aef.png)

**Comment by mfw78** [comment]
For blockscout, this issue may be related: https://github.com/blockscout/blockscout/issues/3633

**Comment by mfw78** [comment]
This is a fundamental issue with the explorers not supporting embedded `SVG` encoded in binary blobs. `blockscout` is slated to address this later in the year. This is all upstream. Closing issue.
